specfile_path: fedora-calculator.spec

files_to_sync:
  - fedora-calculator.spec
  - .packit.yaml

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-rawhide-x86_64
      - fedora-40-x86_64
      - fedora-41-x86_64
      - fedora-42-x86_64

  - job: propose_downstream
    trigger: release
    dist_git_branches:
      - fedora-all
